version: '3.8'

services:
  app:
    container_name: readnshare-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: readnshare-redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: