spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: ${DATA_REDIS_HOST:localhost}
      port: 6379

jwt:
  access:
    expiration: 1800000 #30분

  refresh:
    expiration: 1209600000 #2주


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
