spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: ${DATA_REDIS_HOST:localhost}
      port: 6379

jwt:
  access:
    expiration: 1800000 #30분
  refresh:
    expiration: 1209600000 #2주
  security:
    secretKey: my-custom-secret-key-that-is-very-long

naver:
  book:
    id: ${NAVER_BOOK_ID:none}
    secret: ${NAVER_BOOK_SECRET:none}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

firebase:
  service:
    key: firebase/readnshare-firebase-adminsdk.json