name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create application-prod.yml
        run: |
          echo "${{ secrets.APPLICATION_YML_PROD }}" > src/main/resources/application-prod.yml
        shell: bash

      - name: Create Firebase Directory & JSON
        run: |
          mkdir -p src/main/resources/firebase
          echo '${{ secrets.FIREBASE_ADMIN_JSON }}' > src/main/resources/firebase/readnshare-firebase-adminsdk.json
        shell: bash

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker Build & Push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/readnshare .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/readnshare

      - name: Deploy with Docker Compose via SSH
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            cd /home/compose
            docker-compose pull
            docker-compose up -d --no-deps
            docker image prune -af